### ISSUE TITLE
Running script error

### ISSUE THREAD

**Issue by cheemsbaby** [AnWang-AI/AugABSA#1]
Hello, Mr. Wang.
Your idea of generating sentences from quadruplets in reverse to use as data augmentation is interesting, I'd love to reproduce your work but I'm currently having some minor issues I hope you can help me with.

When I run`bash ./run_semi.sh 0 2` this problem occurs
`Sanity Checking: 0it [00:00, ?it/s]Total examples = 209
Sanity Checking DataLoader 0:   0%|                                                                                                                       | 0/1 [00:00<?, ?it/s]Traceback (most recent call last):
  File "scripts/text2data/main.py", line 230, in <module>
    trainer.fit(tuner)
  File "/root/autodl-tmp/conda/envs/mvp/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "/root/autodl-tmp/conda/envs/mvp/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/root/autodl-tmp/conda/envs/mvp/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/root/autodl-tmp/conda/envs/mvp/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1112, in _run
    results = self._run_stage()
  File "/root/autodl-tmp/conda/envs/mvp/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1191, in _run_stage
    self._run_train()
  File "/root/autodl-tmp/conda/envs/mvp/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1204, in _run_train
    self._run_sanity_check()
  File "/root/autodl-tmp/conda/envs/mvp/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1276, in _run_sanity_check
    val_loop.run()
  File "/root/autodl-tmp/conda/envs/mvp/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/root/autodl-tmp/conda/envs/mvp/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 152, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/root/autodl-tmp/conda/envs/mvp/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/root/autodl-tmp/conda/envs/mvp/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 137, in advance
    output = self._evaluation_step(**kwargs)
  File "/root/autodl-tmp/conda/envs/mvp/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 234, in _evaluation_step
    output = self.trainer._call_strategy_hook(hook_name, *kwargs.values())
  File "/root/autodl-tmp/conda/envs/mvp/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1494, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/root/autodl-tmp/conda/envs/mvp/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 390, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/root/autodl-tmp/absa/AugABSA/scripts/text2data/tuner.py", line 123, in validation_step
    outputs = self.evaluate_step(batch, batch_idx)
  File "/root/autodl-tmp/absa/AugABSA/scripts/text2data/tuner.py", line 214, in evaluate_step
    loss += self._step(batch, True, False)
TypeError: _step() takes 2 positional arguments but 4 were given`

Then I made a change '/AugABSA/scripts/text2data/tuner.py", line 214, in evaluate_step
    loss += self._step(batch, True, False)' to 'loss += self._step(batch)' but after that I got a new error like this '09/22/2023 10:43:57 - INFO - root - Epoch 0 - Val
aspect {'precision': 0, 'recall': 0.0, 'f1': 0}
opinion {'precision': 0, 'recall': 0.0, 'f1': 0}
------ Forward Eval Results ------                                                                                                                                            
Quad: p=0.0000, r=0.0000, f=0.0000                                                                                                                                            
EAEO: p=0.0000, r=0.0000, f=0.0000                                                                                                                                            
EAIO: p=0.0000, r=0.0000, f=0.0000                                                                                                                                            
IAEO: p=0.0000, r=0.0000, f=0.0000                                                                                                                                            
IAIO: p=0.0000, r=0.0000, f=0.0000                                                                                                                                            
Total examples = 834                                                                                                                                                          
Epoch 0:   0%|                                                                                                                                         | 0/11 [00:00<?, ?it/s]/root/autodl-tmp/conda/envs/mvp/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py:362: LightningDeprecationWarning: The NVIDIA/apex AMP implementation has been deprecated upstream. Consequently, its integration inside PyTorch Lightning has been deprecated in v1.9.0 and will be removed in v2.0.0. The `FineTuner.optimizer_step()` hook is overridden, including the `using_native_amp` argument. Removing this argument will avoid this message, you can expect it to return True.
  rank_zero_deprecation(
Traceback (most recent call last):
  File "scripts/text2data/main.py", line 230, in <module>
    trainer.fit(tuner)
  File "/root/autodl-tmp/conda/envs/mvp/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "/root/autodl-tmp/conda/envs/mvp/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/root/autodl-tmp/conda/envs/mvp/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/root/autodl-tmp/conda/envs/mvp/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1112, in _run
    results = self._run_stage()
  File "/root/autodl-tmp/conda/envs/mvp/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1191, in _run_stage
    self._run_train()
  File "/root/autodl-tmp/conda/envs/mvp/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1214, in _run_train
    self.fit_loop.run()
  File "/root/autodl-tmp/conda/envs/mvp/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/root/autodl-tmp/conda/envs/mvp/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 267, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/root/autodl-tmp/conda/envs/mvp/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/root/autodl-tmp/conda/envs/mvp/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 213, in advance
    batch_output = self.batch_loop.run(kwargs)
  File "/root/autodl-tmp/conda/envs/mvp/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/root/autodl-tmp/conda/envs/mvp/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 88, in advance
    outputs = self.optimizer_loop.run(optimizers, kwargs)
  File "/root/autodl-tmp/conda/envs/mvp/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/root/autodl-tmp/conda/envs/mvp/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 202, in advance
    result = self._run_optimization(kwargs, self._optimizers[self.optim_progress.optimizer_position])
  File "/root/autodl-tmp/conda/envs/mvp/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 249, in _run_optimization
    self._optimizer_step(optimizer, opt_idx, kwargs.get("batch_idx", 0), closure)
  File "/root/autodl-tmp/conda/envs/mvp/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 370, in _optimizer_step
    self.trainer._call_lightning_module_hook(
  File "/root/autodl-tmp/conda/envs/mvp/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1356, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/root/autodl-tmp/absa/AugABSA/scripts/text2data/tuner.py", line 335, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/root/autodl-tmp/conda/envs/mvp/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py", line 169, in step
    step_output = self._strategy.optimizer_step(self._optimizer, self._optimizer_idx, closure, **kwargs)
  File "/root/autodl-tmp/conda/envs/mvp/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 234, in optimizer_step
    return self.precision_plugin.optimizer_step(
  File "/root/autodl-tmp/conda/envs/mvp/lib/python3.8/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 119, in optimizer_step
    return optimizer.step(closure=closure, **kwargs)
  File "/root/autodl-tmp/conda/envs/mvp/lib/python3.8/site-packages/torch/optim/lr_scheduler.py", line 65, in wrapper
    return wrapped(*args, **kwargs)
  File "/root/autodl-tmp/conda/envs/mvp/lib/python3.8/site-packages/torch/optim/optimizer.py", line 113, in wrapper
    return func(*args, **kwargs)
  File "/root/autodl-tmp/conda/envs/mvp/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/root/autodl-tmp/conda/envs/mvp/lib/python3.8/site-packages/transformers/optimization.py", line 439, in step
    loss = closure()
  File "/root/autodl-tmp/conda/envs/mvp/lib/python3.8/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 105, in _wrap_closure
    closure_result = closure()
  File "/root/autodl-tmp/conda/envs/mvp/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 149, in __call__
    self._result = self.closure(*args, **kwargs)
  File "/root/autodl-tmp/conda/envs/mvp/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 144, in closure
    self._backward_fn(step_output.closure_loss)
  File "/root/autodl-tmp/conda/envs/mvp/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 305, in backward_fn
    self.trainer._call_strategy_hook("backward", loss, optimizer, opt_idx)
  File "/root/autodl-tmp/conda/envs/mvp/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1494, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/root/autodl-tmp/conda/envs/mvp/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 207, in backward
    self.precision_plugin.backward(closure_loss, self.lightning_module, optimizer, optimizer_idx, *args, **kwargs)
  File "/root/autodl-tmp/conda/envs/mvp/lib/python3.8/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 67, in backward
    model.backward(tensor, optimizer, optimizer_idx, *args, **kwargs)
  File "/root/autodl-tmp/conda/envs/mvp/lib/python3.8/site-packages/pytorch_lightning/core/module.py", line 1498, in backward
    loss.backward(*args, **kwargs)
  File "/root/autodl-tmp/conda/envs/mvp/lib/python3.8/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/root/autodl-tmp/conda/envs/mvp/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
Epoch 0:   0%|          | 0/11 [00:05<?, ?it/s]      '

**Comment by dujiajianbing** [comment]
i have the same problem，how can i solve it?

**Comment by AnWang-AI** [comment]
This issue may be caused by the versions of torch or PyTorch Lightning. I am using torch=1.12.1 and PyTorch Lightning=1.9.5.

**Comment by dujiajianbing** [comment]
and then i have another problem.

Traceback (most recent call last):
  File "scripts/text2data/main.py", line 226, in <module>
    trainer = pl.Trainer(**train_params)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/utilities/argparse.py", line 348, in insert_env_defaults
    return fn(self, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 437, in __init__
    plugins=plugins,
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 202, in __init__
    self._accelerator_flag = self._choose_gpu_accelerator_backend()
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 546, in _choose_gpu_accelerator_backend
    if CUDAAccelerator.is_available():
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/accelerators/cuda.py", line 94, in is_available
    return num_cuda_devices() > 0
  File "/opt/conda/lib/python3.7/site-packages/lightning_fabric/accelerators/cuda.py", line 164, in num_cuda_devices
    nvml_count = _device_count_nvml()
  File "/opt/conda/lib/python3.7/site-packages/lightning_fabric/accelerators/cuda.py", line 314, in _device_count_nvml
    visible_devices = _parse_visible_devices()
  File "/opt/conda/lib/python3.7/site-packages/lightning_fabric/accelerators/cuda.py", line 216, in _parse_visible_devices
    x = _strtoul(elem.strip())
  File "/opt/conda/lib/python3.7/site-packages/lightning_fabric/accelerators/cuda.py", line 194, in _strtoul
    return int(s[:idx]) if idx > 0 else -1
ValueError: invalid literal for int() with base 10: '-'

how can i solve this problem?

**Comment by dujiajianbing** [comment]
> This issue may be caused by the versions of torch or PyTorch Lightning. I am using torch=1.12.1 and PyTorch Lightning=1.9.5.

i use the same version,but still have the problem.



main.py 230 <module>
trainer.fit(tuner)

trainer.py 608 fit
call._call_and_handle_interrupt(

call.py 38 _call_and_handle_interrupt
return trainer_fn(*args, **kwargs)

trainer.py 650 _fit_impl
self._run(model, ckpt_path=self.ckpt_path)

trainer.py 1112 _run
results = self._run_stage()

trainer.py 1191 _run_stage
self._run_train()

trainer.py 1214 _run_train
self.fit_loop.run()

loop.py 199 run
self.advance(*args, **kwargs)

fit_loop.py 267 advance
self._outputs = self.epoch_loop.run(self._data_fetcher)

loop.py 199 run
self.advance(*args, **kwargs)

training_epoch_loop.py 213 advance
batch_output = self.batch_loop.run(kwargs)

loop.py 199 run
self.advance(*args, **kwargs)

training_batch_loop.py 88 advance
outputs = self.optimizer_loop.run(optimizers, kwargs)

loop.py 199 run
self.advance(*args, **kwargs)

optimizer_loop.py 202 advance
result = self._run_optimization(kwargs, self._optimizers[self.optim_progress.optimizer_position])

optimizer_loop.py 249 _run_optimization
self._optimizer_step(optimizer, opt_idx, kwargs.get("batch_idx", 0), closure)

optimizer_loop.py 370 _optimizer_step
self.trainer._call_lightning_module_hook(

trainer.py 1356 _call_lightning_module_hook
output = fn(*args, **kwargs)

tuner.py 334 optimizer_step
optimizer.step(closure=optimizer_closure)

optimizer.py 169 step
step_output = self._strategy.optimizer_step(self._optimizer, self._optimizer_idx, closure, **kwargs)

strategy.py 234 optimizer_step
return self.precision_plugin.optimizer_step(

precision_plugin.py 119 optimizer_step
return optimizer.step(closure=closure, **kwargs)

lr_scheduler.py 65 wrapper
return wrapped(*args, **kwargs)

optimizer.py 113 wrapper
return func(*args, **kwargs)

grad_mode.py 27 decorate_context
return func(*args, **kwargs)

optimization.py 549 step
loss = closure()

precision_plugin.py 105 _wrap_closure
closure_result = closure()

optimizer_loop.py 149 __call__
self._result = self.closure(*args, **kwargs)

optimizer_loop.py 144 closure
self._backward_fn(step_output.closure_loss)

optimizer_loop.py 305 backward_fn
self.trainer._call_strategy_hook("backward", loss, optimizer, opt_idx)

trainer.py 1494 _call_strategy_hook
output = fn(*args, **kwargs)

strategy.py 207 backward
self.precision_plugin.backward(closure_loss, self.lightning_module, optimizer, optimizer_idx, *args, **kwargs)

precision_plugin.py 67 backward
model.backward(tensor, optimizer, optimizer_idx, *args, **kwargs)

module.py 1498 backward
loss.backward(*args, **kwargs)

_tensor.py 396 backward
torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)

__init__.py 173 backward
Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

RuntimeError:
element 0 of tensors does not require grad and does not have a grad_fn
Exception ignored in: <function tqdm.__del__ at 0x7f06d2074dc0>
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/tqdm/std.py", line 1152, in __del__
  File "/root/miniconda3/lib/python3.8/site-packages/tqdm/std.py", line 1306, in close
  File "/root/miniconda3/lib/python3.8/site-packages/tqdm/std.py", line 1499, in display
  File "/root/miniconda3/lib/python3.8/site-packages/tqdm/std.py", line 1155, in __str__
  File "/root/miniconda3/lib/python3.8/site-packages/tqdm/std.py", line 1457, in format_dict
TypeError: cannot unpack non-iterable NoneType object
